# Generated by Django 4.0.1 on 2022-02-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_tag_post_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url_slug',
            field=models.SlugField(default=''),
        ),
    ]
