# Generated by Django 4.0.1 on 2022-02-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_url_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url_slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
